"""The Overview page and the control plane's security posture (§15.1, §17).

The overview is arithmetic over rows the media path writes, and the
arithmetic has rules: a call placed from the browser page is counted apart,
a centre manager's page is their centres' page, and "today" is the Indian
day. These tests write a few calls the way the voice worker would and check
the sums, because a tile that is quietly wrong is worse than one that is
missing.
"""

from __future__ import annotations

import uuid
from collections.abc import AsyncIterator
from datetime import UTC, datetime, timedelta
from typing import Any

import pytest
from httpx import AsyncClient
from sqlalchemy import text
from sqlalchemy.ext.asyncio import async_sessionmaker

from tests.panel_support import act_as
from uaagro_domain.enums import CallDirection, CallOutcome, CallStatus, Role, TelephonyProvider

pytestmark = pytest.mark.integration

_SEVERITY = {"high": 0, "medium": 1, "low": 2}


@pytest.fixture(autouse=True)
def fresh_overview() -> AsyncIterator[None]:
    """Every test computes its own overview rather than reading a neighbour's."""
    from api.routers import panel_overview

    panel_overview.reset_cache()
    yield
    panel_overview.reset_cache()


@pytest.fixture
async def calls(app_engine) -> AsyncIterator[dict[str, Any]]:  # type: ignore[no-untyped-def]
    """A morning's calls, written the way the voice worker writes them.

    Four real calls and one from the browser page: a resolved helpline call,
    a hand-over nobody picked up, a call the agent did not understand, an
    outbound offer that was accepted, and a simulator run with a summary.
    """
    from uaagro_db.models import Call

    maker = async_sessionmaker(app_engine, expire_on_commit=False)
    started = datetime.now(UTC) - timedelta(seconds=30)
    rows: dict[str, Any] = {}

    async with maker() as session:
        await session.execute(text("SELECT set_config('app.role','ops_manager',true)"))
        org = await session.scalar(text("SELECT id FROM organizations LIMIT 1"))
        centre = await session.scalar(text("SELECT id FROM centres ORDER BY code LIMIT 1"))
        other_centre = await session.scalar(
            text("SELECT id FROM centres ORDER BY code DESC LIMIT 1")
        )

        def call(name: str, **fields: Any) -> None:
            row = Call(
                organization_id=org,
                call_ref=f"OVW-{uuid.uuid4().hex[:8].upper()}",
                started_at=started,
                answered_at=started,
                ended_at=started + timedelta(seconds=20),
                duration_seconds=20,
                status=CallStatus.COMPLETED,
                language_final="hi-IN",
                **fields,
            )
            session.add(row)
            rows[name] = row

        call(
            "resolved",
            direction=CallDirection.INBOUND,
            provider=TelephonyProvider.EXOTEL,
            centre_id=centre,
            outcome=CallOutcome.RESOLVED,
            latency_stats={"first_reply_ms": 900},
            intents=["price_enquiry"],
        )
        call(
            "handover",
            direction=CallDirection.INBOUND,
            provider=TelephonyProvider.EXOTEL,
            centre_id=centre,
            outcome=CallOutcome.TRANSFERRED,
            was_transferred=True,
            transfer_completed=False,
            latency_stats={"first_reply_ms": 1500},
            intents=["talk_to_human"],
        )
        call(
            "lost",
            direction=CallDirection.INBOUND,
            provider=TelephonyProvider.EXOTEL,
            centre_id=other_centre,
            outcome=CallOutcome.CALLER_HUNG_UP,
            latency_stats={"first_reply_ms": 700},
            intents=["unknown", "unknown"],
        )
        call(
            "offer",
            direction=CallDirection.OUTBOUND,
            provider=TelephonyProvider.EXOTEL,
            centre_id=centre,
            outcome=CallOutcome.OFFER_ACCEPTED,
            latency_stats={"first_reply_ms": 600},
            intents=["price_enquiry"],
        )
        call(
            "test",
            direction=CallDirection.INBOUND,
            provider=TelephonyProvider.SIMULATOR,
            centre_id=centre,
            outcome=CallOutcome.RESOLVED,
            latency_stats={"first_reply_ms": 400},
            summary_hi="किसान ने डीएपी का रेट पूछा।",
        )
        # The ids are generated by the database, so they exist after the flush.
        await session.flush()
        ids: dict[str, uuid.UUID] = {name: row.id for name, row in rows.items()}
        await session.commit()

    yield {"ids": ids, "centre": centre, "other_centre": other_centre}

    async with maker() as session:
        await session.execute(text("SELECT set_config('app.role','ops_manager',true)"))
        await session.execute(
            text("DELETE FROM calls WHERE id = ANY(:ids)"), {"ids": list(ids.values())}
        )
        await session.commit()


async def _counted(app_engine, *, test: bool) -> int:  # type: ignore[no-untyped-def]
    """What the database says today holds, for the overview to agree with."""
    from api.routers.panel_overview import window_for

    window = window_for("today")
    async with app_engine.connect() as connection:
        await connection.execute(text("SELECT set_config('app.role','ops_manager',true)"))
        return int(
            await connection.scalar(
                text(
                    "SELECT count(*) FROM calls WHERE started_at >= :start AND started_at < :end "
                    "AND (provider = 'simulator') = :test"
                ),
                {"start": window.start, "end": window.end, "test": test},
            )
            or 0
        )


# --------------------------------------------------------------------------- #
# Counts
# --------------------------------------------------------------------------- #


async def test_test_calls_are_counted_apart_from_real_ones(
    panel: AsyncClient, calls: dict[str, Any], app_engine: Any
) -> None:
    act_as(panel, Role.OPS_MANAGER)
    response = await panel.get("/admin/overview?range=today")
    assert response.status_code == 200, response.text
    body = response.json()

    assert body["range"] == "today"
    assert body["calls"]["total"] == await _counted(app_engine, test=False)
    assert body["calls"]["testCalls"] == await _counted(app_engine, test=True)
    assert body["calls"]["testCalls"] >= 1
    assert body["calls"]["total"] >= 4
    assert body["calls"]["inbound"] + body["calls"]["outbound"] == body["calls"]["total"]
    assert body["calls"]["transferred"] >= 1
    # The finished calls add up: answered by the agent, handed over, or missed.
    ended = (
        body["calls"]["answeredByAgent"] + body["calls"]["transferred"] + body["calls"]["missed"]
    )
    assert ended <= body["calls"]["total"]
    assert body["live"]["capacity"] > 0


async def test_the_recent_list_marks_the_test_call_and_carries_its_summary(
    panel: AsyncClient, calls: dict[str, Any]
) -> None:
    act_as(panel, Role.OPS_MANAGER)
    body = (await panel.get("/admin/overview")).json()
    by_id = {row["id"]: row for row in body["recent"]}
    test_call = by_id[str(calls["ids"]["test"])]
    assert test_call["isTest"] is True
    assert test_call["summaryHi"] == "किसान ने डीएपी का रेट पूछा।"
    assert by_id[str(calls["ids"]["resolved"])]["isTest"] is False
    assert len(body["recent"]) <= 10


async def test_outcomes_speed_and_questions_come_from_the_calls(
    panel: AsyncClient, calls: dict[str, Any]
) -> None:
    act_as(panel, Role.OPS_MANAGER)
    body = (await panel.get("/admin/overview")).json()

    outcomes = {row["key"]: row for row in body["outcomes"]}
    assert outcomes["resolved"]["label"] == "Resolved"
    assert outcomes["offer_accepted"]["count"] >= 1
    counts = [row["count"] for row in body["outcomes"]]
    assert counts == sorted(counts, reverse=True)

    assert body["speed"]["firstReplyP50Ms"] is not None
    assert body["speed"]["firstReplyP95Ms"] >= body["speed"]["firstReplyP50Ms"]

    questions = {row["intent"]: row for row in body["topQuestions"]}
    assert questions["price_enquiry"]["count"] >= 2
    assert questions["price_enquiry"]["label"] == "What is the price?"
    # Not a question: a call the agent did not understand.
    assert "unknown" not in questions
    assert len(body["topQuestions"]) <= 8


async def test_by_hour_is_the_indian_day_and_adds_up(
    panel: AsyncClient, calls: dict[str, Any]
) -> None:
    act_as(panel, Role.OPS_MANAGER)
    today = (await panel.get("/admin/overview?range=today")).json()
    assert len(today["byHour"]) == 24
    assert today["byHour"][0]["hour"] == "00:00"
    assert today["byHour"][23]["hour"] == "23:00"
    assert sum(r["inbound"] + r["outbound"] for r in today["byHour"]) == today["calls"]["total"]

    week = (await panel.get("/admin/overview?range=7d")).json()
    assert len(week["byHour"]) == 7
    assert week["byHour"][-1]["hour"].split(" ")[0] in {
        "Mon",
        "Tue",
        "Wed",
        "Thu",
        "Fri",
        "Sat",
        "Sun",
    }
    assert week["calls"]["total"] >= today["calls"]["total"]

    month = (await panel.get("/admin/overview?range=30d")).json()
    assert len(month["byHour"]) == 30
    assert month["from"] <= week["from"] <= today["from"]


async def test_attention_names_the_handover_and_the_call_nobody_understood(
    panel: AsyncClient, calls: dict[str, Any]
) -> None:
    act_as(panel, Role.OPS_MANAGER)
    body = (await panel.get("/admin/overview")).json()
    items = body["attention"]
    assert len(items) <= 12
    ranks = [_SEVERITY[item["severity"]] for item in items]
    assert ranks == sorted(ranks), "most urgent first"

    by_kind = {item["kind"]: item for item in items}
    handover = by_kind["transfer_failed"]
    assert handover["severity"] == "high"
    assert handover["href"] == f"/calls/{calls['ids']['handover']}"
    assert handover["count"] >= 1

    lost = by_kind["unanswered"]
    assert lost["href"] == f"/calls/{calls['ids']['lost']}"
    assert lost["count"] >= 1
    for item in items:
        assert item["title"], item
        assert isinstance(item["count"], int)


async def test_a_centre_manager_sees_only_their_centres_calls(
    panel: AsyncClient, calls: dict[str, Any]
) -> None:
    act_as(panel, Role.OPS_MANAGER)
    everyone = (await panel.get("/admin/overview")).json()

    act_as(panel, Role.CENTRE_MANAGER, centres=(calls["centre"],))
    mine = (await panel.get("/admin/overview")).json()
    assert mine["calls"]["total"] < everyone["calls"]["total"]
    assert str(calls["ids"]["lost"]) not in {row["id"] for row in mine["recent"]}
    assert str(calls["ids"]["resolved"]) in {row["id"] for row in mine["recent"]}


async def test_the_overview_is_served_from_a_short_cache(panel: AsyncClient) -> None:
    from api.routers import panel_overview

    act_as(panel, Role.OPS_MANAGER)
    first = (await panel.get("/admin/overview")).json()
    second = (await panel.get("/admin/overview")).json()
    assert first["generatedAt"] == second["generatedAt"]

    panel_overview.reset_cache()
    third = (await panel.get("/admin/overview")).json()
    assert third["generatedAt"] >= first["generatedAt"]


async def test_an_unknown_range_is_refused_and_the_page_needs_a_manager(
    panel: AsyncClient,
) -> None:
    act_as(panel, Role.OPS_MANAGER)
    assert (await panel.get("/admin/overview?range=fortnight")).status_code == 422
    act_as(panel, Role.AGRONOMIST)
    assert (await panel.get("/admin/overview")).status_code == 403
    act_as(panel, Role.READ_ONLY)
    assert (await panel.get("/admin/telephony")).status_code == 403


# --------------------------------------------------------------------------- #
# Telephony
# --------------------------------------------------------------------------- #


async def test_telephony_reports_the_simulator_and_the_browser_page(
    panel: AsyncClient, settings_env: Any
) -> None:
    settings_env(TELEPHONY_PROVIDER="simulator", INBOUND_DID="+919876501234")
    act_as(panel, Role.CENTRE_MANAGER)
    body = (await panel.get("/admin/telephony")).json()
    assert body["provider"] == "simulator"
    assert body["mode"] == "simulator"
    assert body["configured"] is True
    assert body["remedy"] is None
    # Masked to the last four digits, never the number.
    assert body["inboundNumber"].endswith("1234")
    assert "9876501234" not in body["inboundNumber"]
    # Development only: the test environment gets no link to the page.
    assert body["browserCallUrl"] is None


def test_telephony_names_the_missing_variables() -> None:
    from api.routers.panel_overview import telephony_status
    from uaagro_domain.settings import Settings

    status = telephony_status(
        Settings(
            app_env="development",
            telephony_provider="exotel",
            exotel_sid=None,
            exotel_api_key=None,
            exotel_api_token=None,
            inbound_did=None,
            voice_worker_public_url="http://127.0.0.1:8080/",
        )
    )
    assert status.mode == "live"
    assert status.configured is False
    assert "EXOTEL_SID" in (status.remedy or "")
    assert "TELEPHONY_PROVIDER=simulator" in (status.remedy or "")
    assert status.inboundNumber is None
    assert status.browserCallUrl == "http://127.0.0.1:8090/call"


# --------------------------------------------------------------------------- #
# Security
# --------------------------------------------------------------------------- #


async def test_every_response_forbids_caching(panel: AsyncClient) -> None:
    act_as(panel, Role.OPS_MANAGER)
    for path in ("/admin/telephony", "/admin/overview", f"/admin/calls/{uuid.uuid4()}"):
        response = await panel.get(path)
        assert "no-store" in response.headers["cache-control"], path
    # A route that sets its own words keeps them and gains the one that matters.
    response = await panel.get("/health/live")
    assert response.headers["cache-control"] == "no-store"


async def test_metrics_need_the_internal_token_outside_development(
    panel: AsyncClient, settings_env: Any
) -> None:
    settings_env(INTERNAL_API_TOKEN="test-internal-token-not-a-secret")
    assert (await panel.get("/metrics")).status_code == 403
    assert (await panel.get("/metrics", headers={"x-internal-token": "wrong"})).status_code == 403
    scraped = await panel.get(
        "/metrics", headers={"x-internal-token": "test-internal-token-not-a-secret"}
    )
    assert scraped.status_code == 200


async def test_the_documentation_is_not_served_outside_development(panel: AsyncClient) -> None:
    assert (await panel.get("/docs")).status_code == 404
    assert (await panel.get("/openapi.json")).status_code == 404
