"""Shared domain types for the UA Agro voice platform.

Imported by every other package. Contains no I/O, no database access and no
vendor SDKs -- it is the vocabulary the rest of the system speaks.
"""

from __future__ import annotations

from .enums import (
    ApprovalState,
    AudioCodec,
    AuditAction,
    CallDirection,
    CallOutcome,
    CallStatus,
    CampaignStatus,
    ConsentType,
    ContactStatus,
    DoseBasis,
    ExclusionReason,
    FlowType,
    Intent,
    LandUnit,
    ProductCategory,
    ProductType,
    QualityTier,
    Role,
    Season,
    TelephonyProvider,
    TicketPriority,
    TicketType,
    TransferReason,
    TurnRole,
    TurnStrategy,
    WhatsAppTemplate,
)
from .errors import (
    AuthenticationError,
    AuthorizationError,
    ComplianceError,
    ConfigurationError,
    ConflictError,
    MissingCredentialError,
    NotFoundError,
    RestrictedProductError,
    ServiceUnavailableError,
    UAAgroError,
    UnapprovedAdvisoryError,
    ValidationError,
    VendorTimeoutError,
    VendorUnavailableError,
)
from .money import CostBreakdown, CostComponent, Money, RateUnit, VendorRate
from .phone import Msisdn, is_promotional_series, normalise_msisdn, redact
from .settings import Defaults, LanguageRoute, Settings, get_defaults, get_settings
from .units import LandArea, bags_for_quantity, from_acres, scale_dose, to_acres

__all__ = [
    "ApprovalState",
    "AudioCodec",
    "AuditAction",
    "AuthenticationError",
    "AuthorizationError",
    "CallDirection",
    "CallOutcome",
    "CallStatus",
    "CampaignStatus",
    "ComplianceError",
    "ConfigurationError",
    "ConflictError",
    "ConsentType",
    "ContactStatus",
    "CostBreakdown",
    "CostComponent",
    "Defaults",
    "DoseBasis",
    "ExclusionReason",
    "FlowType",
    "Intent",
    "LandArea",
    "LandUnit",
    "LanguageRoute",
    "MissingCredentialError",
    "Money",
    "Msisdn",
    "NotFoundError",
    "ProductCategory",
    "ProductType",
    "QualityTier",
    "RateUnit",
    "RestrictedProductError",
    "Role",
    "Season",
    "ServiceUnavailableError",
    "Settings",
    "TelephonyProvider",
    "TicketPriority",
    "TicketType",
    "TransferReason",
    "TurnRole",
    "TurnStrategy",
    "UAAgroError",
    "UnapprovedAdvisoryError",
    "ValidationError",
    "VendorRate",
    "VendorTimeoutError",
    "VendorUnavailableError",
    "WhatsAppTemplate",
    "bags_for_quantity",
    "from_acres",
    "get_defaults",
    "get_settings",
    "is_promotional_series",
    "normalise_msisdn",
    "redact",
    "scale_dose",
    "to_acres",
]
